apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-nginx-deployment
  labels:
    app.kubernetes.io/name: php-nginx
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: php-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: php-nginx
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: php-blog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: php-nginx
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: php-blog
    spec:
      initContainers:
        - name: init-mysql
          image: fahimlahcen/php-project-fpm
          command:
            - 'sh'
            - '-c'
            - |
              until nc -z mysql-service 3306;
              do
                echo "waiting for mysql";
                sleep 2;
              done;
              echo "mysql is ready";
              php /app/data/migration.php
              echo "seed script executed";
      containers:
        - name: php-fpm
          image: fahimlahcen/php-project-fpm
          ports:
            - containerPort: 9000
        - name: nginx
          image: fahimlahcen/nginx-project
          ports:
            - containerPort: 80